name: Build and Push Golang Image to AWS ECR

on:
  push:
    tags:
      - 'v1.0.*'

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Updated to latest version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4  # Updated to latest version
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2  # Updated to latest version

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: property-bulls-server-prod
        IMAGE_TAG: ${{ github.ref }}  # Uses GitHub tag reference directly
      run: |
        # Extract the tag name from GITHUB_REF
        TAG_NAME=${{ github.ref }}
        TAG_NAME=${TAG_NAME#refs/tags/}  # Strip off 'refs/tags/' part

        # Build and push the Docker image with the tag
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_NAME .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_NAME


